/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.Color;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;

/**
 *
 * @author dell
 */
public class Brute extends javax.swing.JFrame {
    private Object highlighter;
     private DefaultHighlighter.DefaultHighlightPainter highlightPainter;

    /** Creates new form Brute */
    public Brute() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BruteBook = new javax.swing.JLayeredPane();
        btnEnter = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Journal = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrintJournal = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        btnExit2 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        treasure = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BruteBook.setOpaque(true);
        BruteBook.setVisible(false);
        BruteBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnter.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(55, 44, 25));
        btnEnter.setText("ENTER");
        btnEnter.setBorder(null);
        btnEnter.setContentAreaFilled(false);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        BruteBook.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 80, 40));

        btnBack.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Menu");
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        BruteBook.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(226, 215, 203));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jScrollPane2.setHorizontalScrollBar(null);

        Journal.setBackground(new java.awt.Color(226, 215, 203));
        Journal.setColumns(20);
        Journal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Journal.setLineWrap(true);
        Journal.setRows(5);
        Journal.setText("Paste your text here\n");
        Journal.setBorder(null);
        jScrollPane2.setViewportView(Journal);

        BruteBook.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 260));

        jScrollPane1.setBackground(new java.awt.Color(226, 215, 203));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(75, 58, 40));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        PrintJournal.setBackground(new java.awt.Color(226, 215, 203));
        PrintJournal.setColumns(20);
        PrintJournal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        PrintJournal.setLineWrap(true);
        PrintJournal.setRows(5);
        PrintJournal.setBorder(null);
        jScrollPane1.setViewportView(PrintJournal);

        BruteBook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 220, 250));

        searchField.setBackground(new java.awt.Color(226, 215, 203));
        searchField.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        searchField.setText("Enter word here");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        BruteBook.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 120, 30));

        btnExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CloseButton.png"))); // NOI18N
        btnExit2.setBorder(null);
        btnExit2.setContentAreaFilled(false);
        btnExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit2MouseClicked(evt);
            }
        });
        BruteBook.add(btnExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 90, 80));

        btnSearch.setBorder(null);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        BruteBook.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Brute_Book.png"))); // NOI18N
        BruteBook.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        jPanel1.add(BruteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));
        jPanel1.add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CloseButton.png"))); // NOI18N
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Open the Treasure Box");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        treasure.setBorderPainted(false);
        treasure.setContentAreaFilled(false);
        treasure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        treasure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treasureMouseClicked(evt);
            }
        });
        jPanel1.add(treasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 110, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BB.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Exit", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
       if(confirm == 0){
           this.dispose();
       }
    }//GEN-LAST:event_btnExitActionPerformed

    private void treasureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treasureMouseClicked
        BruteBook.setVisible(true);
    }//GEN-LAST:event_treasureMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void btnExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit2MouseClicked
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Exit", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
       if(confirm == 0){
           this.dispose();
       }
    }//GEN-LAST:event_btnExit2MouseClicked

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
       String j = Journal.getText();
       PrintJournal.append(j);
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         String search = searchField.getText();
        Document length = PrintJournal.getDocument();
        PrintJournal.getHighlighter().removeAllHighlights();

         try {
                    for (int index = 0; index + search.length() < length.getLength(); index++) {
                        String match = length.getText(index, search.length());
                        
                        if (search.equals(match)) {
                                javax.swing.text.DefaultHighlighter.DefaultHighlightPainter highlightPainter =
                                    new     javax.swing.text.DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
                            PrintJournal.getHighlighter().addHighlight(index, index + search.length(),
                                    highlightPainter);
                        }
                       
                    }
                } catch (BadLocationException exp) {
                    exp.printStackTrace();
                }    
 
      
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Gui_Menu menu = new Gui_Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new Gui_Menu().setVisible(true);
        Gui_Input.inputArray.clear();
        Gui_Menu.activeBubble = 0;
        Gui_Menu.activeHeap = 0;
        Gui_Menu.activeInsertion = 0;
        Gui_Menu.activeSelection =0;
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BruteBook;
    private javax.swing.JTextArea Journal;
    private javax.swing.JTextArea PrintJournal;
    private javax.swing.JLabel arrow;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton treasure;
    // End of variables declaration//GEN-END:variables

}
