/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Gui_Menu extends javax.swing.JFrame {
    public static int activeBubble = 0;
    public static int activeSelection = 0;
    public static int activeInsertion = 0;
    public static int activeHeap= 0;


    /**
     * Creates new form Menu
     */
    public Gui_Menu() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHeap = new javax.swing.JButton();
        btnInsertion = new javax.swing.JButton();
        btnSelection = new javax.swing.JButton();
        btnBrute = new javax.swing.JButton();
        btnBubble = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeap.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnHeap.setForeground(new java.awt.Color(240, 240, 240));
        btnHeap.setText("HEAP");
        btnHeap.setContentAreaFilled(false);
        btnHeap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHeap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHeapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHeapMouseExited(evt);
            }
        });
        btnHeap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeapActionPerformed(evt);
            }
        });
        jPanel1.add(btnHeap, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 300, 110, 40));

        btnInsertion.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnInsertion.setForeground(new java.awt.Color(240, 240, 240));
        btnInsertion.setText("INSERTION");
        btnInsertion.setContentAreaFilled(false);
        btnInsertion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertionMouseExited(evt);
            }
        });
        btnInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 40));

        btnSelection.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnSelection.setForeground(new java.awt.Color(240, 240, 240));
        btnSelection.setText("SELECTION");
        btnSelection.setContentAreaFilled(false);
        btnSelection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectionMouseExited(evt);
            }
        });
        btnSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 255, -1, 40));

        btnBrute.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnBrute.setForeground(new java.awt.Color(255, 255, 255));
        btnBrute.setText("BRUTE");
        btnBrute.setContentAreaFilled(false);
        btnBrute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBruteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBruteMouseExited(evt);
            }
        });
        btnBrute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBruteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrute, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 400, 120, 40));

        btnBubble.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnBubble.setForeground(new java.awt.Color(240, 240, 240));
        btnBubble.setText("BUBBLE");
        btnBubble.setContentAreaFilled(false);
        btnBubble.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBubble.setHideActionText(true);
        btnBubble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBubbleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBubbleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBubbleMouseExited(evt);
            }
        });
        btnBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleActionPerformed(evt);
            }
        });
        jPanel1.add(btnBubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 165, -1, 40));

        btnExit.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(240, 240, 240));
        btnExit.setText("EXIT");
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 443, 100, 40));

        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 90, 90));

        backround.setBackground(new java.awt.Color(255, 255, 255));
        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Algo_Menu.png"))); // NOI18N
        jPanel1.add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 513));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleActionPerformed
        this.dispose();
        activeBubble = 1;
        new Gui_Input().setVisible(true);
        
    }//GEN-LAST:event_btnBubbleActionPerformed

    private void btnInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertionActionPerformed
        this.dispose();
        new Gui_Input().setVisible(true);
        activeInsertion = 1;
      
    }//GEN-LAST:event_btnInsertionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Exit", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
       if(confirm == 0){
           this.dispose();
       }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBubbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBubbleMouseClicked
        
        
    }//GEN-LAST:event_btnBubbleMouseClicked

    private void btnBubbleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBubbleMouseEntered
        btnBubble.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnBubbleMouseEntered

    private void btnBubbleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBubbleMouseExited
        btnBubble.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBubbleMouseExited

    private void btnInsertionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertionMouseEntered
        btnInsertion.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnInsertionMouseEntered

    private void btnInsertionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertionMouseExited
        btnInsertion.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnInsertionMouseExited

    private void btnSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectionMouseEntered
        btnSelection.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnSelectionMouseEntered

    private void btnSelectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectionMouseExited
        btnSelection.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSelectionMouseExited

    private void btnHeapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHeapMouseEntered
        btnHeap.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnHeapMouseEntered

    private void btnHeapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHeapMouseExited
        btnHeap.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnHeapMouseExited

    private void btnBruteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBruteMouseEntered
        btnBrute.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnBruteMouseEntered

    private void btnBruteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBruteMouseExited
        btnBrute.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBruteMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
       btnExit.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
       btnExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionActionPerformed
        this.dispose();
        activeSelection = 1;
        new Gui_Input().setVisible(true);
        
    }//GEN-LAST:event_btnSelectionActionPerformed

    private void btnHeapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeapActionPerformed
        this.dispose();
        activeHeap = 1;
        new Gui_Input().setVisible(true);
        
    }//GEN-LAST:event_btnHeapActionPerformed

    private void btnBruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBruteActionPerformed
        this.dispose();
        new Brute().setVisible(true);
        
    }//GEN-LAST:event_btnBruteActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Exit", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
       if(confirm == 0){
           this.dispose();
       }
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JButton btnBrute;
    private javax.swing.JButton btnBubble;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHeap;
    private javax.swing.JButton btnInsertion;
    private javax.swing.JButton btnSelection;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
