/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Gui_Input extends javax.swing.JFrame {
   
   public static ArrayList<Integer> inputArray = new ArrayList<Integer>();
  // public static int[] inputArray;
    /**
     * Creates new form Gui_Input
     */
    public Gui_Input() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        input_tf = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        error_msg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextArea = new javax.swing.JTextArea();
        btnSort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 9, 90, 90));

        input_tf.setBackground(new java.awt.Color(236, 230, 227));
        input_tf.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        input_tf.setForeground(new java.awt.Color(69, 54, 39));
        input_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_tf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tfActionPerformed(evt);
            }
        });
        input_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_tfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_tfKeyTyped(evt);
            }
        });
        jPanel1.add(input_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 140, 110));

        btnAdd.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(240, 240, 240));
        btnAdd.setText("ADD");
        btnAdd.setToolTipText("");
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        error_msg.setFont(new java.awt.Font("Digital tech", 1, 12)); // NOI18N
        error_msg.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(error_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 190, 20));

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setEnabled(false);
        TextArea.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 210, 140));

        btnSort.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        btnSort.setForeground(new java.awt.Color(240, 240, 240));
        btnSort.setText("SORT");
        btnSort.setContentAreaFilled(false);
        btnSort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSortMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSortMouseExited(evt);
            }
        });
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        jPanel1.add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 445, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Algo_Input.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 513));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        if (Gui_Menu.activeInsertion == 1){
            JOptionPane.showMessageDialog(rootPane, "INSERTION");
            this.dispose();
            new Gui_Simulation().setVisible(true);
        }
        else if(Gui_Menu.activeBubble == 1){
            JOptionPane.showMessageDialog(rootPane, "Bubble");
            this.dispose();
            new Gui_Simulation().setVisible(true);
        }
         else if(Gui_Menu.activeHeap == 1){
            JOptionPane.showMessageDialog(rootPane, "Heap");
            this.dispose();
            new Gui_Simulation().setVisible(true);
        }
         else if(Gui_Menu.activeSelection == 1){
            JOptionPane.showMessageDialog(rootPane, "Selection");
            this.dispose();
            new Gui_Simulation().setVisible(true);
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         int inputTF = Integer.parseInt(input_tf.getText());
         inputArray.add(inputTF);
        // inputArray[] = new int[inputTF];
        
        
        TextArea.append("" + inputTF +"    ");
        input_tf.setText(null);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int i = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit the program?", "Exit", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if(i == 0){
            
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSortMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortMouseEntered
        btnSort.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnSortMouseEntered

    private void btnSortMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortMouseExited
        btnSort.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSortMouseExited

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
       btnAdd.setForeground(Color.decode("#EE9A4D"));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAddMouseExited

    private void input_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tfActionPerformed

    private void input_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_tfKeyTyped
    
    }//GEN-LAST:event_input_tfKeyTyped

    private void input_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_tfKeyPressed
      //  int inputTF = Integer.parseInt(input_tf.getText());
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9'){
           error_msg.setText("");
           input_tf.setEditable(true);
        }
     
        else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
            input_tf.setEditable(true);
            error_msg.setText("");
        }
        else if (evt.getKeyChar() >= 'A' && evt.getKeyChar() >= 'Z'){
            input_tf.setEditable(false);
            error_msg.setText("Invalid input!");
          //  error_msg.setForeground(Color.decode("#9F000F"));
           // error_msg.setFont();
    }
    }//GEN-LAST:event_input_tfKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnSort;
    private javax.swing.JLabel error_msg;
    public javax.swing.JTextField input_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
